language: python

cache: pip

matrix:
  include:
    - python: 3.5
    - python: 3.5
      env: NUMPY_VERSION="<1.14.0"
    - python: 3.6
    - python: 3.7
    - python: 3.7
      env:
        - NUMPY_EXPERIMENTAL_ARRAY_FUNCTION="1"
        - NUMPY_VERSION="==1.16.2"
      dist: xenial

install:
  - ./ci/01-install.sh

script:
  - pytest

after_success:
  - codecov

notifications:
  email: false
