version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - restore_cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
      - run:
          name: Install package
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[docs]
            pip uninstall sparse
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "setup.py" }}
          paths:
            - "venv"
      - run:
          name: Build DevDocs
          command: |
            . venv/bin/activate
            pip install -e .[docs]
            sphinx-build -b html docs/ _build/html
      - store_artifacts:
          path: _build/html
