name: sparse-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - numpy
  - numba:llvmlite
  - numba:numba
  - scipy
  - dask
  - pytest
  - pytest-cov
  - pytest-xdist
  - pip:
    - finch-tensor>=0.2.2
    - finch-mlir>=0.0.2
    - pytest-codspeed
