name: sparse-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - pip:
    - finch-tensor>=0.2.12
    - finch-mlir>=0.0.2
    - pytest-codspeed
    - numpy
    - numba
    - scipy
    - dask
    - pytest
    - pytest-cov
    - pytest-xdist
